name: My first workflow
on:
  - push
jobs:
  my-first-job:
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
        py_version:
          - '3.11.3'
          - '3.8'
          - '3.10'
    runs-on: "${{ matrix.os }}-latest"
    steps:
      - run: echo ciao
      - name: Checkout the repo
        uses: actions/checkout@main
      - uses: actions/setup-python@v4
        with:
          python-version: '${{ matrix.py_version }}'
      - name: Setup the virtual environment
        run: python -m venv .venv
      - run: source .venv/bin/activate
        if: ${{ matrix.os != 'windows' }}
      - run: ls -ahl .venv/
        shell: bash
        if: ${{ matrix.os == 'windows' }}
      - run: source .venv/Scripts/activate.ps1
        if: ${{ matrix.os == 'windows' }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: python -m py_compile macd.py
      - run: echo SUCCESS!
